In [7]:
import numpy as np
from scipy import stats
import pandas as pd

# read in csv data
MGO_Maine = np.genfromtxt('MgO_Maine.csv', skip_header=1, delimiter=',')
print(MGO_Maine)

# Now the list form
MGO_Maine_list = np.genfromtxt('MgO_Maine_list.csv', skip_header=1,
                               delimiter=',', autostrip=True,
                               dtype=[('f0', '<i8'), ('f1', '<U20')])
print(MGO_Maine_list)

# Another way
import csv
reader = csv.reader('MGO_Maine.csv', delimiter=',')
for line in reader:
    print(', '.join(line))

[[  7.   4.   1.]
 [  8.   5.   2.]
 [ 10.   7.   4.]
 [ 11.   8.   5.]]
[( 7, 'Mount Mica') ( 8, 'Mount Mica') (10, 'Mount Mica')
 (11, 'Mount Mica') ( 4, 'Sebago Batholith') ( 5, 'Sebago Batholith')
 ( 7, 'Sebago Batholith') ( 8, 'Sebago Batholith') ( 1, 'Black Mountain')
 ( 2, 'Black Mountain') ( 4, 'Black Mountain') ( 5, 'Black Mountain')]
M
G
O
_
M
a
i
n
e
.
c
s
v


In [4]:
# Start over following instructions :)
import numpy as np
from scipy import stats
import pandas as pd

# Basic way of opening a file
fhandle = open('MgO_Maine.csv')
fhandle.read()

'Mount Mica,Sebago Batholith,Black Mountain\n7,         4,               1\n8,         5,               2\n10,        7,               4\n11,        8,               5\n'

In [5]:
# using numpy
data = np.genfromtxt('MgO_Maine.csv', skip_header=1, delimiter=',')
data

array([[  7.,   4.,   1.],
       [  8.,   5.,   2.],
       [ 10.,   7.,   4.],
       [ 11.,   8.,   5.]])

In [8]:
np.shape(data)

(4, 3)

In [9]:
np.ndim(data)

2

In [10]:
data[:, 0]
# shows 0th column - note it displays as a row.

array([  7.,   8.,  10.,  11.])

In [11]:
data[:2, 0]

array([ 7.,  8.])

In [12]:
np.mean(data)  #  all values lumped

6.0

In [13]:
np.mean(data, axis=0) # down across rows, taking mean of each column

array([ 9.,  6.,  3.])

In [14]:
np.mean(data, axis=1) # taking mean of each row

array([ 4.,  5.,  7.,  8.])

In [15]:
data.T  # transpose!  does not change data

array([[  7.,   8.,  10.,  11.],
       [  4.,   5.,   7.,   8.],
       [  1.,   2.,   4.,   5.]])

In [17]:
np.tile([1,2,3],[3,1])  # repeat 1st argument 3 times down, 1 across

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [18]:
np.zeros([2,7])

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [19]:
np.ones([2,7])

array([[ 1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.]])

In [21]:
np.nan # all operations give nan

nan

In [22]:
np.ones([2,7])*np.nan
# for memory allocation
# also note that nans remaining can flag a problem



array([[ nan,  nan,  nan,  nan,  nan,  nan,  nan],
       [ nan,  nan,  nan,  nan,  nan,  nan,  nan]])