In [1]:
import numpy as np
from scipy.spatial import distance

In [2]:
# repeat what we did in class by hand:
u = [415, 200, 310, 411]
v = [615, 100, 330, 203]
q = [614, 101, 331, 202]

In [4]:
data = np.array([u, v, q])
print(data)

[[415 200 310 411]
 [615 100 330 203]
 [614 101 331 202]]


In [9]:
data.T
print(data)
# outputs transformed version, doesn't change data
data.T

[[415 200 310 411]
 [615 100 330 203]
 [614 101 331 202]]


array([[415, 615, 614],
       [200, 100, 101],
       [310, 330, 331],
       [411, 203, 202]])

In [12]:
dist=distance.pdist(data, 'braycurtis')
distmatrix = distance.squareform(dist)
distmatrix

array([[ 0.        ,  0.20433437,  0.20433437],
       [ 0.20433437,  0.        ,  0.00160256],
       [ 0.20433437,  0.00160256,  0.        ]])