In [1]:
# exceptions
# an example of conditional execution

In [5]:
a = 'year'
b = 2018

try:
    combined = a + b
except:
    print('a and b are incompatible.')
    combined = str(a) + str(b)
    
print(combined)
        

a and b are incompatible.
year2018


In [7]:
# loops
# while loop  - indefinite loop - until a certain condition is met
#

i = 0
while i < 5:
    i = i + 1
    print(i)

print('done with while loop')

1
2
3
4
5
done with while loop


In [10]:
# for loop - repeats a statement for every element of a sequence
# sequences - list, array, string (a seq of characters), tuple

name_list = ['Bob', 'Jane', 'Mary']
for name in name_list:
    print('Hello', name)
    
print('done with for loop')

Hello Bob
Hello Jane
Hello Mary
done with for loop


In [11]:
import numpy as np
np.arange(5)

array([0, 1, 2, 3, 4])

In [12]:
print(np.arange(2,5,0.5))

[ 2.   2.5  3.   3.5  4.   4.5]


In [16]:
for i in np.arange(5):
    print(i*2)
    print()
    print(2**i)

0

1
2

2
4

4
6

8
8

16


In [18]:
# without numpy, but less flexible.
for i in range(5):
    print(i*2)

0
2
4
6
8


In [19]:
# Loop and count at the same time
for i, name in enumerate(name_list):
    print(i, name)

0 Bob
1 Jane
2 Mary


In [20]:
# 2/6 handout
# Problem 4 (1st one)
# Cumulative sum of an array
values = [1, 3, 6, 4, 7]
cumsum = 0
for val in values:
    cumsum = cumsum + val
    print(cumsum)
    

1
4
10
14
21


In [21]:
# 2/6 handout, 2nd number 4
# store cumulative sum in another array.  Use np.append()
import numpy as np
cumsum = 0
cum_array = [];
for val in values:
    cumsum = cumsum + val
    cum_array = np.append(cum_array, cumsum)
    
print(cum_array)

[  1.   4.  10.  14.  21.]


In [28]:
# 2/6 handout, 3rd number 4
# Function returning an array containing the first n Fibonnaci numbers
def fib(n):
    ''' Returns the first n numbers of the Fibonacci sequence'''
    if n == 1:
        return [1]
    elif n == 2: 
        return [1, 1]
    
    vals = [1, 1]
    for i in np.arange(2, n):
        vals = np.append(vals, vals[i-1] + vals[i-2])
        
    return vals

davinci_code = fib(8)
print(davinci_code)

[ 1  1  2  3  5  8 13 21]


In [44]:
# read in csv data
MGO_Maine = np.genfromtxt('MGO_Maine.csv', skip_header=1, delimiter=',')
print(MGO_Maine)

# Now the list form
MGO_Maine_list = np.genfromtxt('MGO_Maine_list.csv', skip_header=1,
                               delimiter=',', autostrip=True,
                               dtype=[('f0', '<i8'), ('f1', '<U20')])
print(MGO_Maine_list)

# Another way
import csv
reader = csv.reader('MGO_Maine.csv', delimiter=',')
for line in reader:
    print ', '.join(line)


SyntaxError: invalid syntax (<ipython-input-44-80e2dfeb9104>, line 15)